server:
  port: 8888


logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chendb/egova-cloud.git
          searchPaths: egova-config-repo
